INSERT INTO PESSOA ( NOME, CEP ) VALUES ('Welington', 41150901);
INSERT INTO PESSOA ( NOME ) VALUES ('Joana');
INSERT INTO PESSOA ( NOME ) VALUES ('Paulo');
INSERT INTO PESSOA ( NOME ) VALUES ('Wel');